### ISSUE TITLE
support for baubles

### ISSUE THREAD

**Issue by 0Navis0** [61352151511/Durability-Show#5]
It would be really nice if the mod supported baubles and showed the necklases, rings and necklases with their durability like it does with armors, tools and weapons.

**Comment by 61352151511** [comment]
The next release will have support for baubles.

**Comment by 0Navis0** [comment]
It would be nice you retragrade this update for 1.10.2 ;)

**Comment by 61352151511** [comment]
Are there specific mods that you are wanting to use that have not updated to 1.11? It's always better for mods to update than for me to support others staying behind by updating for older versions of Minecraft.

**Comment by 0Navis0** [comment]
1.11 is still unstable and a lot of mods still didn't update to this version, many people (including me) still plays to 1.10.2 ;)

**Comment by 61352151511** [comment]
1.11 has a recommended build, therefore even though it may be unstable, it is the recommended version and the best one to use in my opinion. I understand that you play 1.10.2 but my perspective is that people should always use the latest version. If people don't use 1.11 it will always be unstable because no one will report issues. I've had no issues updating my mods and others shouldn't have issues too.
